export const SETTINGS_REQUEST = 'SETTINGS_REQUEST';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_FAIL = 'SETTINGS_FAIL';


export const SETTINGS_CREATE_REQUEST = 'SETTINGS_CREATE_REQUEST';
export const SETTINGS_CREATE_SUCCESS = 'SETTINGS_CREATE_SUCCESS';
export const SETTINGS_CREATE_FAIL = 'SETTINGS_CREATE_FAIL';


